### ISSUE TITLE
DxLoading Button Animation

### ISSUE THREAD

**Issue by VinayVanama** [StevenDXC/DxLoadingButton#1]
How to stop the animation by just calling a method like **loadingSuccessful()** instead of adding qualifier lb to the method ?

**Comment by StevenDXC** [comment]
stop loading animation and restore to button view ?

**Comment by StevenDXC** [comment]
stop loading animation and restore to Button view?

**Comment by StevenDXC** [comment]
@VinayVanama 

stop loading animation and restore to button view?

**Comment by VinayVanama** [comment]
Actually I just need a simple thing, As soon as I click on Login button it need to validate the uname and passowrd. if it matches button should animate and show the check symbol,if it didnt match it should show the cross symbol.

**Comment by StevenDXC** [comment]
@VinayVanama 
source code updated, see DemoActivity.

**Comment by VinayVanama** [comment]
WOW.....I liked it thanx
