### ISSUE TITLE
the text of button is not centered.

### ISSUE THREAD

**Issue by matghazaryan** [StevenDXC/DxLoadingButton#21]
Why button text is not centered. Why this is happening?

![screenshot 2018-03-16 11 55 41](https://user-images.githubusercontent.com/5268958/37509513-139f3b20-2911-11e8-943e-135c7535c6e3.png)

**Comment by SkyleKayma** [comment]
It's actually clearly centered in the screenshot that you give ... There is 118px on both side of the text, and 14px at the top and at the bottom. Can't see issue here :/
