### ISSUE TITLE
Problem background button

### ISSUE THREAD

**Issue by Fast0n** [StevenDXC/DxLoadingButton#23]
`        <com.dx.dxloadingbutton.lib.LoadingButton
            android:id="@+id/add"
            android:layout_width="fill_parent"
            android:layout_height="48dp"
            android:layout_marginBottom="8dp"
            android:layout_marginEnd="16dp"
            android:layout_marginStart="16dp"
            android:layout_marginTop="8dp"
            android:background="@drawable/round_corner_spiner"
            android:textColor="@android:color/white"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.501"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/linearLayout2"
            app:lb_btnText="Add" />`

![screenshot_1530838807](https://user-images.githubusercontent.com/5260133/42354718-01d0421c-80c9-11e8-8e56-946e7856e09e.png)

**Comment by StevenDXC** [comment]
the LoadingButton not support set background, you can change LoadingButton style by set backgroundShader and cornerRadius
