### ISSUE TITLE
Probem when soft input open

### ISSUE THREAD

**Issue by radeshf** [StevenDXC/DxLoadingButton#26]
I use android 9 and this test is on genymotion.

when i set `windowSoftInputMode` to `adjustResize` the button will shrink. when click on it small circle turns.

When soft input is closed. it's good

![screenshot-۲۰۱۹-۰۵-۲۵_۱۲ ۲۵ ۴۰ ۵۵۶](https://user-images.githubusercontent.com/20123581/59997085-39ff1500-9671-11e9-8e45-5ff1ac43d670.png)

When soft input is open

![screenshot-۲۰۱۹-۰۵-۲۵_۱۲ ۲۳ ۱۰ ۵۹۵](https://user-images.githubusercontent.com/20123581/59997090-408d8c80-9671-11e9-9035-e9739d51e7f3.png)

**Comment by StevenDXC** [comment]
please update to version 2.3, set lb_min_height  value, it will fixed
