### ISSUE TITLE
Set the font color lead to collapse

### ISSUE THREAD

**Issue by LowLowCoder-Mel** [StevenDXC/DxLoadingButton#28]
https://github.com/StevenDXC/DxLoadingButton/blob/04a5e064ec5e4e5045167323115c445da5d0b2f9/library/src/main/res/values/attrs.xml#L5

I give button font sets a color # FF95B7E4 lead to collapse, I will change to color it works here

**Comment by StevenDXC** [comment]
version 2.4 fixed this error
