### ISSUE TITLE
Rendering problems.

### ISSUE THREAD

**Issue by panosmir** [StevenDXC/DxLoadingButton#5]
I have added the Gradle dependency and it syncs correctly. But I get "Rendering problems". I have added the xmlns:app="http://schemas.android.com/apk/res-auto", still nothing. Also I noticed that if I go inside the buttons block and I want to use the autocomplete for "app:" it doesn't work, it says "No suggestions". Any ideas about that?

**Comment by StevenDXC** [comment]
I have updated the demo app module, fix the wrong widget name in layout.xml. try again pls.
