### ISSUE TITLE
No method to set text dynamically in Java code!!

### ISSUE THREAD

**Issue by MzeeAlii** [StevenDXC/DxLoadingButton#9]
I mean, really? How's `setText()` method not there yet? I think changing button text dynamically through Java code would be one important feature when loading has failed. Think about this, instead of resetting to "Submit" you set the text to.. ... "Try Again" or something like that. Do I make sense? :frowning_face: 
And thanks for the lib. Nice work! :+1:

**Comment by StevenDXC** [comment]
I have add setText method in 1.4 release. you can change the text by the method in java code.

**Comment by MzeeAlii** [comment]
And how could that be done exactly? I've tried `button.setText("Some Text")` and Android Studio cannot resolve the method..

**Comment by StevenDXC** [comment]
check your project dependency  is 1.4 release. I have add the method, see https://github.com/StevenDXC/DxLoadingButton/blob/master/library/src/main/java/com/dx/dxloadingbutton/lib/LoadingButton.java, line 303
